### ISSUE TITLE
Override existing menu entry

### ISSUE THREAD

**Issue by antony-jr** [TheFutureShell/QtUpdateBridges#2]
Some applications already have a "Check for updates" menu entry, e.g., here:

https://github.com/Subsurface-divelog/subsurface/blob/30f2d16dabd49ec0cb871f18ec1bb69f21478020/desktop-widgets/mainwindow.ui#L118-L126

It would be awesome if we could override the existing one (or attach our functionality to it), not just add another menu entry.

**Issue opened by:** @probonopd

**Comment by antony-jr** [comment]
**CC**: @probonopd 

Now you can override existing menu entries. First you need the QObject name of the QMenu or QMenuBar then you will just need the substring or string pattern of the QAction::text() to override it.
Here is a complete script.   
After the script finishes , the new version is saved simply as ```Subsurface-x86_64.AppImage```

```
#!/usr/bin/env bash

# Get subsurface from upstream
wget -c http://subsurface-divelog.org/downloads/Subsurface-4.8.6-x86_64.AppImage

# Make it executable
chmod +x Subsurface-4.8.6-x86_64.AppImage

# Extract contents of AppImage
./Subsurface-4.8.6-x86_64.AppImage --appimage-extract

# Configure
cat > updatedeployqt.json <<EOF
{
   // Always use AppImageUpdater for AppImages
   "bridge" : "AppImageUpdater",

   // Use this to comply with GDPR 
   "manual-update-check" : {
       
       // The QObject name where 'Check for Update' has to integrated
       "qmenu-name" : "menuHelp" ,

       // Overrides any QAction with the given substring as text in the given QMenu
       "qaction-to-override" : "Check for updates"
   }
}
EOF


# Get and run updatedeployqt
wget -O updatedeployqt-x86_64.AppImage "https://git.io/fj4CH"
chmod +x ./updatedeployqt-x86_64.AppImage

# Deploy updater
./updatedeployqt-x86_64.AppImage  squashfs-root/

# Recreate AppImage
wget -c "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
chmod +x ./appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage squashfs-root/ --no-appstream \
         -u $(./Subsurface-4.8.6-x86_64.AppImage --appimage-updateinfo)
```

Here are the screenshots ,

![Screenshot_20190606_230524](https://user-images.githubusercontent.com/33930174/59054120-a677c700-88b0-11e9-9601-7abdf224a776.png)
![Screenshot_20190606_230755](https://user-images.githubusercontent.com/33930174/59054121-a7105d80-88b0-11e9-82f4-0bd02d8b2f04.png)
![Screenshot_20190606_230817](https://user-images.githubusercontent.com/33930174/59054124-a7105d80-88b0-11e9-8579-96a61195e663.png)
![Screenshot_20190606_230830](https://user-images.githubusercontent.com/33930174/59054137-b099c580-88b0-11e9-84ed-f0430ce9cc86.png)
![Screenshot_20190606_230841](https://user-images.githubusercontent.com/33930174/59054138-b1325c00-88b0-11e9-97b7-dce90ea9a410.png)

**Comment by probonopd** [comment]
Bravo! This is really cool!

**Comment by antony-jr** [comment]
You know whats really cool , When this is **programming language independent**. (Still has a lot of issues , for some reason it crashes when the program quits , I suspect this is because of freeing of memory but only with the injector the crash does not happen. Python does not go well with Qt's event loop)

![Screenshot_20190606_235531](https://user-images.githubusercontent.com/33930174/59056911-d629cd80-88b6-11e9-9039-83f76eba0d5d.png)
