### ISSUE TITLE
Can't override existing menu entry that has "_" character

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/QtUpdateBridges#4]
![mumble](https://user-images.githubusercontent.com/2480569/59183906-8409d600-8b5c-11e9-959a-d2a51a3acb7d.png)

This is the menu item in the UI file:
https://github.com/mumble-voip/mumble/blob/755c2905c0c9ee6a21d816db6e66bc24a96f739d/src/mumble/MainWindow.ui#L69

This is the string in the UI file:
https://github.com/mumble-voip/mumble/blob/755c2905c0c9ee6a21d816db6e66bc24a96f739d/src/mumble/MainWindow.ui#L667

```
#!/usr/bin/env bash

# Get Mumble from upstream
wget -c https://github.com/probonopd/mumble/releases/download/continuous/Mumble-5ffa1a4-x86_64.AppImage

# Make it executable
chmod +x Mumble-*-x86_64.AppImage

# Extract contents of AppImage
./Mumble-*-x86_64.AppImage --appimage-extract

# Configure
cat > updatedeployqt.json <<EOF
{
   // Always use AppImageUpdater for AppImages
   "bridge" : "AppImageUpdater",

   // Use this to comply with GDPR 
   "manual-update-check" : {
       
       // The QObject name where 'Check for Update' has to integrated
       "qmenu-name" : "qmHelp" ,

       // Overrides any QAction with the given substring as text in the given QMenu
       "qaction-to-override" : "Check for &amp;Updates"
   }
}
EOF

# Get and run updatedeployqt
wget -O updatedeployqt-x86_64.AppImage "https://git.io/fj4CH"
chmod +x ./updatedeployqt-x86_64.AppImage

# Deploy updater
./updatedeployqt-x86_64.AppImage  squashfs-root/

# Recreate AppImage
wget -c "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
chmod +x ./appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage squashfs-root/ --no-appstream \
         -u $(./Mumble-*-x86_64.AppImage --appimage-updateinfo)

```

**Comment by probonopd** [comment]
If I understand it correctly, I need the QObject name for the first but the literal string for the second.

```
       // The QObject name where 'Check for Update' has to integrated
       "qmenu-name" : "qmHelp" ,

       // Overrides any QAction with the given substring as text in the given QMenu
       "qaction-to-override" : "Check for &amp;Updates"
```

Is that

1.  correct?
2. Could we have it accept both QObject or strings in both places?
3. Would it be possible to "guesstimate" the correct entry by using the first menu with a QObject name that contains "Help" (case-insensitive) and therein the first menu entry with a QObject name that contains "Update" or "Version" (case-insensitive)?

**Comment by probonopd** [comment]
With

```
       "qaction-to-override" : "Check for"
```

it works :+1:

**Comment by antony-jr** [comment]
> 1. Is that correct?

Yes and no. Now we check both the title and the QObject name of the QMenu and QAction to override.

> 2. Could we have it accept both QObject or strings in both places?

As of the latest release we check the QObject name or text of the required QWidget with the given string. In the next release we can give a option to only do the integration if it is QObject name strictly matches and not the text and vice-versa.

> 3. Would it be possible to "guesstimate" the correct entry by using the first menu with a QObject name that contains "Help" (case-insensitive) and therein the first menu entry with a QObject name that contains "Update" or "Version" (case-insensitive)?

Maybe in the future release but with explicit permission from the developer.

**Comment by probonopd** [comment]
> Maybe in the future release but with explicit permission from the developer.

What do you mean by "explicit permission from the developer"? I just want to make it as simple as possible for application developers to use `updatedeployqt`.

**Comment by antony-jr** [comment]
> What do you mean by "explicit permission from the developer"? I just want to make it as simple as possible for application developers to use updatedeployqt.

You know sometimes guessing is a disaster. What happens if we integrate the update check option into menu bar in a tool box ?(in case the Application has a toolbar of some sort). We can only guesstimate if the developer deploying the updater explicitly passes a sign of approval. (like a command line arguement?)

**Comment by probonopd** [comment]
Well, isn't the developer using `updatedeployqt` sign of approval?

**Comment by antony-jr** [comment]
> Well, isn't the developer using updatedeployqt sign of approval?

I guess so. So by default we guesstimate everything?

**Comment by probonopd** [comment]
Yes.
