### ISSUE TITLE
"You have" shows different version/commit

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/QtUpdateBridges#8]
Mumble compiles in the commit hash at build time, see the title bar.

The Software Update dialog shows another commit hash in "you have". Why?

![](https://user-images.githubusercontent.com/2480569/59207493-b1737580-8b96-11e9-9f48-e77ab628b08c.png)

Which one is correct?

This is the AppImage file:
https://github.com/probonopd/mumble/releases/download/old/Mumble-7a563e2-x86_64.AppImage

**Comment by antony-jr** [comment]
I'm currently out of station, I will not be able to do anything for 2 days. The hash is not a git commit, its the SHA-1 hash present in the .zsync file.

**Comment by antony-jr** [comment]
closing in favor of #7
